version: '3'

services:
  be_geziekibi:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile if not named "Dockerfile"
    deploy:
      resources:
        limits:
          cpus: '0.90'
          # memory: 400M
    command: /bin/sh -c "echo 'Running API on production!' && npm run build && npm start"
    ports:
      - '4000:4000'
    env_file:
      - ./config/prod.env
