export const INTERFACE_TYPE = {
  UnitOfWork: Symbol.for('UnitOfWork'),
  Logger: Symbol.for('Logger'),
  IDatabaseService: Symbol.for('IDatabaseService'),
  JsonWebTokenService: Symbol.for('JsonWebTokenService'),
  IJsonWebTokenService: Symbol.for('IJsonWebTokenService'),
  AuthController: Symbol.for('AuthController'),
  IAuthService: Symbol.for('IAuthService'),
  IAuthRepository: Symbol.for('IAuthRepository'),
  TagController: Symbol.for('TagController'),
  ITagService: Symbol.for('ITagService'),
  ITagRepository: Symbol.for('ITagRepository'),
  TourCategoryController: Symbol.for('TourCategoryController'),
  ITourCategoryService: Symbol.for('ITourCategoryService'),
  ITourCategoryRepository: Symbol.for('ITourCategoryRepository'),
};
